name: linting,testing,building
on:
  push:
    branches: [master]
jobs:
 pipeline:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node: [ 18.x ]

   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
          node-version: ${{ matrix.node }}
     - name: install modules
       run: npm install
     - name: build production
       run: npm run build:prod
     - name: run style-lint
       run: npm run styleLint
     - name: run unit
       run: npm run unit
     - name: run lint
       run: npm run lint
