name: linting,testing,building
on:
  push:
    branches: [master]
jobs:
 pipeline:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node: [18x]

   steps:
     - name: run style-lint
       run: npm run styleLint
     - name: run unit
       run: npm run unit
     - name: run lint
       run: npm run lint
